---
- name: Create templates for Azure Cosmos DB
  template:
    src: "{{ item }}.j2"
    dest: "/tmp/{{ item }}"
  with_items:
    - "cosmosdb-simple.yml"
    - "cosmosdb-dynamic.yml"

- name: Set facts for Azure Cosmos DB
  set_fact:
    simple_template: "{{ lookup('file', '/tmp/cosmosdb-simple.yml') | from_yaml }}"
    dynamic_template: "{{ lookup('file', '/tmp/cosmosdb-dynamic.yml') | from_yaml }}"

- name: Provision one Azure Cosmos DB using inline parameters and using a simple template
  azure_rm_deployment:
    subscription_id: "{{ az_subscription_id }}"
    client_id: "{{ az_client_id }}"
    secret: "{{ az_client_secret }}"
    tenant: "{{ az_tenant_id }}"
    location: "{{ az_location }}"
    resource_group_name: "{{ az_resource_group }}"
    template: "{{ simple_template }}"
    parameters:
      name:
        value: "{{ az_name_prefix }}cdb01"
      location:
        value: "{{ az_location }}"
      locationName:
        value: "{{ az_location_name }}"
      defaultExperience:
        value: Cassandra
  when: az_number_of == 1

- name: Provision two Azure Cosmos DBs using parameters from a list variable and using a simple template
  azure_rm_deployment:
    subscription_id: "{{ az_subscription_id }}"
    client_id: "{{ az_client_id }}"
    secret: "{{ az_client_secret }}"
    tenant: "{{ az_tenant_id }}"
    location: "{{ az_location }}"
    resource_group_name: "{{ az_resource_group }}"
    template: "{{ simple_template }}"
    parameters: "{{ item }}"
  loop: "{{ az_cosmos_db }}"
  when: az_number_of == 2 and az_cosmos_db is defined

- name: Provision three Azure Cosmos DBs using list variables and Jinja2
  azure_rm_deployment:
    subscription_id: "{{ az_subscription_id }}"
    client_id: "{{ az_client_id }}"
    secret: "{{ az_client_secret }}"
    tenant: "{{ az_tenant_id }}"
    location: "{{ az_location }}"
    resource_group_name: "{{ az_resource_group }}"
    template: "{{ dynamic_template }}"
  when: az_number_of == 3
