---
- name: Create Azure SQL server and databases
  import_tasks: sql.yml
  when: az_resource | lower == 'sql'

- name: Create one Azure Cosmos DBs
  import_tasks: static.yml
  when:
    - az_resource | lower == 'cosmosdb'
    - az_number_of == 1

- name: Create one Azure Cosmos DBs
  import_tasks: static.yml
  when:
    - az_resource | lower == 'cosmosdb'
    - az_number_of > 1
