---
- name: Create Azure SQL server and databases
  import_tasks: sql.yml
  when: az_resource | lower == 'sql'

- name: Create one or more Azure Cosmos DBs
  import_tasks: cosmosdb.yml
  when: az_resource | lower == 'cosmosdb'
