---
- hosts: localhost
  vars:
    az_tenant_id: "{{ vault_az_tenant_id }}"
    az_client_id: "{{ vault_az_client_id }}"
    az_client_secret: "{{ vault_az_client_secret }}"
    az_subscription_id: "{{ vault_az_subscription_id }}"
    az_token_url: "https://login.microsoftonline.com/{{ az_tenant_id }}/oauth2/token"
    az_token_body: "resource=https://management.core.windows.net/&client_id={{ az_client_id }}&grant_type=client_credentials&client_secret={{ az_client_secret }}"
    az_mgnt_url: "https://management.azure.com/subscriptions/{{ az_subscription_id }}"
    az_res_admin_url: "{{ az_mgnt_url }}/resourceGroups/{{ az_resource_group }}"
    az_web_app: devops-demo-app
    az_allowed_ip: 10.10.1.4
  tasks:
    - name: Login to Azure
      uri:
        url: "{{ az_token_url }}"
        method: POST
        body: "{{ az_token_body }}"
        headers:
          Content-Type: "application/x-www-form-urlencoded"
        status_code: 200
      register: login
      no_log: True

    - name: Setting Bearer token as fact
      set_fact:
        azure_bearer: "{{ login.json.access_token }}"
      no_log: True

    - name: Set IP restrictions
      uri:
        url: "{{ az_res_admin_url }}/providers/Microsoft.Web/sites/{{ az_web_app }}/config/web?api-version=2018-02-01"
        method: PATCH
        body:
          properties:
            ipSecurityRestrictions:
              - ipAddress: "{{ az_allowed_ip }}/31"
                action: "Allow"
                priority: 300
                name: "Allow demo"
        body_format: json
        headers:
          Authorization: "Bearer {{ azure_bearer }}"
        status_code: 200

    # - name: Set IP restrictions with a loop (which won't work like this)
    #   uri:
    #     url: "{{ az_res_admin_url }}/providers/Microsoft.Web/sites/{{ az_web_app }}/config/web?api-version=2018-02-01"
    #     method: PATCH
    #     body:
    #       properties:
    #         ipSecurityRestrictions:
    #           - ipAddress: "{{ item }}/31"
    #             action: "Allow"
    #             priority: 300
    #             name: "Allow demo"
    #     body_format: json
    #     headers:
    #       Authorization: "Bearer {{ azure_bearer }}"
    #     status_code: 200
    #   with_items:
    #     - 10.10.1.1
    #     - 10.10.1.2
    #     - 10.10.1.3
    #     - 10.10.1.4
