---
- hosts: localhost
  vars:
    az_resource: sql
    az_name_prefix: ansiblecphm
    az_sql_server_name: "{{ az_name_prefix }}srv"
    az_sql_username: "{{ vault_az_sql_username }}"
    az_sql_password: "{{ vault_az_sql_password }}"
    az_sql_database_name_prefix: "{{ az_name_prefix }}db"
    az_sql_databases:
      - create_mode: default
        edition: free
      - create_mode: default
        edition: basic

  roles:
    - meetup-demo
