---
- hosts: localhost
  vars:
    az_resource: sql
    az_sql_server_name: ansiblecphsrv
    az_sql_username: "{{ vault_az_sql_username }}"
    az_sql_password: "{{ vault_az_sql_password }}"
    az_sql_database_name_prefix: ansiblecphdb
    az_sql_databases:
      - create_mode: default
        edition: free
      - create_mode: default
        edition: basic

  roles:
    - meetup-demo
